
CREATE DATABASE BD_INQUILINOS;
USE BD_INQUILINOS;
CREATE TABLE TB_DPTO(
NRO_DPTO INT PRIMARY KEY NOT NULL,
UBICACION  VARCHAR(20) NOT NULL,
DESCRIPCION VARCHAR(40) ,
AREA 	DOUBLE NOT NULL,
ESTADO VARCHAR(20) NOT NULL,##OCUPADO -EN ALQUILER -MANTENIMIENTO
OBSERVACION VARCHAR(20),
PRECIO_DPTO DOUBLE NOT NULL
);
CREATE TABLE TB_ARRENDATARIO(
DNI INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
FECHA_NAC VARCHAR(8) NOT NULL,
NACIONALIDAD VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(60) ,
PERSONA_RESPONSABLE_PAGO VARCHAR(81),
NRO_PERS_VIVIRAN INT,
CUANTOS_APORTAN INT,
TIPO_TRABAJO_TITULAR VARCHAR(30),
FECHA_MUDANZA VARCHAR(8) NOT NULL,
FECHA_INGRESO VARCHAR(8) NOT NULL, ##FECHA DE INGRESO 
PERSONA_EMERGENCIA VARCHAR(30),
NRO_EMERGENCIA INT,
ESTADO VARCHAR(20)NOT NULL,##VIGENTE -RETIRADO 
DURACION_ALQUILER INT NOT NULL## SERA CONCIDERADO POR MESES == 1 AÑO =12 MESES °° 1/2 AÑO = 6 MESES 
);

 CREATE TABLE TB_CONTRATO(
 NRO INT AUTO_INCREMENT PRIMARY KEY,
 DNI INT NOT NULL,
 NRO_DPTO INT NOT NULL,
 PRECIO_DPTO DOUBLE NOT NULL,
 GARANTIA DOUBLE NOT NULL,
 DURACION_ALQUILER INT NOT NULL,
 FECHA_INGRESO VARCHAR(8) NOT NULL,
 FECHA_SALIDA VARCHAR(8) NOT NULL,
 TIPO_CONTRATO VARCHAR(30)NOT NULL ## INICIO , RENOVACION, TEMPORAL
 );